# Generated by Django 4.2.8 on 2024-05-15 07:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_user_first_name_user_last_name_user_phone_number_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Gallery',
            new_name='ProjectGallery',
        ),
        migrations.RemoveField(
            model_name='project',
            name='desc',
        ),
        migrations.AddField(
            model_name='project',
            name='is_approved',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='project',
            name='sub_header',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Sub Header'),
        ),
        migrations.AlterField(
            model_name='project',
            name='content',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Main Content'),
        ),
    ]
