# Generated by Django 5.0.6 on 2024-05-29 00:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_project_image_project_volunteer_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='project',
            name='image',
        ),
        migrations.AddField(
            model_name='project',
            name='post_date',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Post Date'),
        ),
        migrations.AddField(
            model_name='project',
            name='post_time',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Post Time'),
        ),
        migrations.CreateModel(
            name='ProjectGallery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(blank=True, null=True, upload_to='images/')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.project')),
            ],
        ),
    ]
