# Generated by Django 5.0.6 on 2024-06-01 22:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_remove_project_image_project_post_date_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='projectgallery',
            name='project',
        ),
        migrations.AddField(
            model_name='project',
            name='images',
            field=models.ManyToManyField(blank=True, to='api.projectgallery'),
        ),
    ]
