# Generated by Django 5.0.6 on 2024-06-17 17:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_alter_blog_content_alter_project_content_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='blog',
            name='images',
        ),
        migrations.AddField(
            model_name='blog',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='images/'),
        ),
        migrations.AlterField(
            model_name='blog',
            name='content',
            field=models.TextField(blank=True, max_length=10000, null=True, verbose_name='Main Content'),
        ),
        migrations.AlterField(
            model_name='blog',
            name='sub_header',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Sub Header'),
        ),
        migrations.AlterField(
            model_name='blog',
            name='title',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Title'),
        ),
        migrations.AlterField(
            model_name='project',
            name='content',
            field=models.TextField(blank=True, max_length=10000, null=True, verbose_name='Main Content'),
        ),
    ]
