# Generated by Django 5.0.6 on 2024-06-18 21:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0011_blog_author_blog_category_alter_blog_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='milestone',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Milestone'),
        ),
    ]
